package com.zz.pay.enums;

public enum ResConstants {
    SUCCESS("200", "成功"),
    DATABASE_ERROR("1000", "DataBase请求错误"),
    SERVICE_ERROR("2000", "API请求错误"),
    API_ERROR("3000", "API请求错误"),
    PARAM_NOT_RIGHT("1001", "入参数值不合法"),
    PARAM_NOT_NULL("1002", "必要参数不能为空"),
    QUERY_DATA_EXCEPTION("1003", "查询数据异常"),
    QUERY_DATA_EXIST("1004", "查询数据存在"),
    QUERY_DATA_NOT_EXIST("1005", "查询数据不存在"),
    ADD_DATA_FAIL("1006", "添加数据失败"),
    UPD_DATA_FAIL("1007", "更新数据失败"),
    DEL_DATA_FAIL("1008", "删除数据失败"),
    OBJECT_NOT_NULL("1009", "入参对象不能为空"),
    INTERFACE_ACCESS_EXCEPTION("1010", "接口调用获取异常"),
    RUNTIME_EXCEPTION("1011", "运行时异常"),
    API_SIGNATURE_EXCEPTION("1012", "数字验签异常"),
    API_SIGNATURE_OUT_TIME_EXCEPTION("1013", "数字签名秘钥已失效"),
    API_SIGNATURE_NOT_EXIST_EXCEPTION("1014", "数字签名非法不存在"),
    HTTPS_REQUEST_EXCEPTION("1130", "https请求异常"),
    HTTPS_COMMUNICATION_FAIL("1131", "https网络通讯失败"),
    HTTPS_REQUERT_FAIL("1132", "https请求处理结果失败"),
    USERNAME_NON_EXISTENT("1501", "用户名不存在"),
    PASSWORD_FAIL_EXCEPTION("1502", "登陆密码不正确"),
    IMG_AUTHCODE_EXCEPTION("1503", "图片验证码不正确"),
    PASSWORD_FAIL_UPDATE("1504", "修改密码失败"),
    PASSWORD_FAIL_EXCEPTION_SET_CODE("1505", "登陆密码不正确"),
    IMG_AUTHCODE_EXCEPTION_SET_CODE("1506", "图片验证码不正确"),
    USER_LOCKED_EXCEPTION("1507", "用户已被锁定"),
    USER_LOCKED_FAILED_EXCEPTION("1508", "用户锁定失败"),
    ILLEGAL_PHONE_NUM_STYLE_EXCEPTION("1509", "错误的手机格式"),
    ILLEGAL_PASSWORD_STYLE_EXCEPTION("1510", "错误的密码格式"),
    IMG_AUTHCODE_EXCEPTION_OUT_TIME("1511", "图片验证码超时，请重新获取"),
    PAY_CASH_BIG100_EXCEPTION("1520 ", "余额大于100时,提现额度必须大于100"),
    PAY_CASH_SMALL100_EXCEPTION("1521 ", "账户余额小于100时需全额提取"),
    PAY_CASH_TIMES_EXCEPTION("1522 ", "提现次数大于限定次数"),
    PAY_CASH_AMOUNT_EXCEPTION("1523", "可用额度小于提现额度"),
    PAY_CASH_EXCEPTION("1524", "提现异常"),
    WITHDRAW_NOT_INVEST("1525", "体验金收益\n需投资后才能提现"),
    PAY_CASH_SMALL_FREE_EXCEPTION("1526", "剩余金额小于提现手续费"),
    WITHDRAW_RELEASE_FROZEN_FAIL("1527", "提现解冻失败！"),
    ADD_REGINFO_EXCEPTION("1531", "记录注册来路异常"),
    DIGITAL_SIGN_EXCEPTION("1532", "数字签名访问异常"),
    SMS_SEND_EXCEPTION("1533", "短信发送异常"),
    SMS_TIME_EXCEPTION("1534", "短信发送时间异常"),
    SMS_AUTHCODE_EXCEPTION("1535", "短信验证码不正确"),
    SMS_SERNTIME_EXCEPTION("1536", "短信发送时间间隔太小，涉嫌恶意操作"),
    SMS_SERNUM_EXCEPTION("1537", "短信发送次数异常，次数超过合法阈值，涉嫌恶意操作"),
    USERNAME_ALREADY_EXIST_EXCEPTION("1538", "用户已注册"),
    SMS_HAS_RAN_OUT_EXCEPTION("1539", "短信验证码已失效"),
    EMPLOYEE_NON_EXISTENT("1540", "员工不存在！"),
    EMPLOYEE_IS_REGISTER("1541", "员工不存在！"),
    PUT_DATA_CACHE_EXCEPTION("1631", "将数据放到缓存中异常"),
    GET_DATA_CACHE_EXCEPTION("1632", "根据KEY获取数据异常"),
    SEND_MQ_EXCEPTION("1641", "发送MQ消息异常"),
    INIT_MQ_EXCEPTION("1642", "发送MQ消息异常"),
    MOBLIE_FORMAT_EXCEPTION("1671", "手机号码格式不正确"),
    CREATE_SINA_MEMBER_FAIL("1691", "创建用户解析失败"),
    CREATE_SINA_MEMBER_QEQUEST_FAIL("1692", "创建用户请求失败"),
    SINA_PAY_EXCEPTION("1721", "新浪支付统一异常"),
    PAY_FROZEN_AMOUNT_EXCEPTION("1720", "账户冻结异常"),
    ACCOUNT_CASH_PASSWORD_WRONG("1701", "交易密码错误"),
    BANK_NOT_MATCH("1691", "银行卡不匹配"),
    USER_CARD_IS_BINDED("1620", "该银行卡已经绑定过,请核对!"),
    USER_IS_NOT_BINDED("1621", "该用户未绑定过银行卡，请核对！"),
    BONUS_STATUS_EXCEPTION("1801", "红包状态异常不可分享"),
    BOUNS_NOT_EXISTS("1802", "红包被抢光或不存在"),
    BOUNS_RECEIVE_REPEATED("1803", "不能重复抢红包"),
    BONUS_NOT_EXISTS("1804", "红包券不存在"),
    REGISTER_INVITE_CODE_INVIDE("1805", "邀请码无效"),
    BORROW_supplement_FAILT("1806", "盖标失败"),
    BONUS_IS＿EXP("1807", "分享红包已过期"),
    ACTIV_INVEST_NOT_EXIST("1851", "该活动标的已经被抢完，欢迎下次光临"),
    ACTIV_INVITE_USER_NOT("1852", "您目前还未达到拿大奖的要求，赶快去邀请好友吧"),
    ACTIVITY_DRAW_NOT_EXIST("1901", "抽奖活动不存在或已过期"),
    USER_NOT_LUCKYDRAW("1902", "用户没有抽奖机会"),
    USER_GETLUCKDRAW_EXCEPTION("1903", "用户获取抽奖机会失败"),
    INVEST_FAIL("1921", "投资失败"),
    INVEST_STATUS_NOT_INVALID("1922", "标当前不可投"),
    INVEST_BORROW_REMAIN_AMOUNT_NOT_ENOUGH("1923", "可投额度不足"),
    INVEST_BORROW_MIN_INVEST_AMOUNT("1924", "用户可用额度少于投资额度"),
    INVEST_BORROW_START_INVERST_TIME("1925", "标未到开始时间"),
    BORROW_NOT_EXISTS("1926", "标不存在"),
    USER_ACCOUNT_NOT_EXISTS("1927", "用户账户不存在"),
    BORROW_NID_IS_NOT_NULL("1928", "标ID不能为空"),
    USER_ID_IS_NOT_NULL("1929", "用户ID不能为空"),
    BORROW_INVEST_AMOUNT_IS_NOT_NULL("1930", "投资金额不能为空"),
    BORROW_INVEST_AMOUNT_LT_MIN_INVEST("1931", "投资金额不能少于最低投资额度"),
    BORROW_INVEST_TIME_TYPE_NOT_INVAILD("1932", "标时间类型不合法"),
    BORROW_EXPECTED_REVENUE_NOT_MATCH("1933", "传入的预期收益与服务器端计算结果不匹配"),
    BORROW_INVEST_USER_NOT_BIND_CARD("1934", "用户未绑卡"),
    BORROW_FULL("1935", "很遗憾，下手慢了项目以募集成功"),
    BORROW_INVEST_NID_IS_NOT_NULL("1936", "NID不能为空"),
    BORROW_INVEST_CASH_PASSWORD_IS_NOT_NULL("1937", "交易密码不能为空"),
    BORROW_INVEST_CASH_PASSWORD_WRON("1938", "交易密码错"),
    BORROW_INVEST_NID_IS_NOT_INVAILD("1939", "NID无效"),
    BORROW_INVEST_COUPON_NOT_INVALID("1940", "优惠码无效"),
    BORROW_INVEST_BOUNS_COUNT_OVER("1941", "红包券数量超出系统限定"),
    BORROW_INVEST_BONUS_AMOUNT_OVER("1942", "红包券金额超出系统限定"),
    BORROW_INVEST_CASHBACK_MISMATCH_RULE("1943", "立返券规则不匹配"),
    BORROW_INVEST_UPDATE_4CASHBACK_FAIL("1944", "立返券返现失败"),
    BORROW_INVEST_OVER_MAX_INVEST_AMOUNT("1945", "投资额度超过标的最大可投额度"),
    BORROW_INFEST_EXPIRY("1946", "标已过截止日"),
    BORROW_INVEST_COUPON_UNDER_MIN_AMOUNT("1947", "投资额度不能少于红包券的最低投资额度"),
    NOVICE_IS_INVEST_ONE("1948", "新手标只能购买一次！"),
    INVEST_SECKILL_SUM_EXCEPTION("1949", "同一个用户购买单个聚财宝类型标的总额上限为10000元！"),
    INVEST_INVITE_EXCEPTION("1950", "投资邀请码必须是注册时推荐人邀请码！"),
    INVEST_RELEASE_FROZEN_FAIL("1951", "投资解冻失败！"),
    USER_ACCOUNT_AMOUNT_NOT_ZERO("1952", "用户账户可用余额必须为0"),
    REMAIN_AMOUNT_ALL_INVEST("1953", "需要一次性全部购买标的剩余额度"),
    USER_IS_ENTRUST("2001", "用户已设置委托扣款"),
    BORROW_REPLAN_EXCEPTION("2010", "生成还款计划异常"),
    DEMAND_GRANT_INTEREST_RATE_IS_NULL("2021", "昨日活期标利息为空"),
    DEMAND_GRANT_INTEREST_GRANT_ERROR("2022", "昨日活期标利息发放失败"),
    SINA_VAILD_EXCEEPTION("2030", "sina 返回值解析失败"),
    SINA_FOPAY_EXCEEPTION("2031", "投资失败"),
    AUTO_SIGN_AGREEMENT_EXCEEPTION("2032", "自动签约借款协议失败"),
    AUTO_RECHARGE("2033", "自动充值失败"),
    TOKEN_NOT_EXISTS("1027", "明文直接返回输入值");

    private final String code;
    private final String msg;

    private ResConstants(String code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public String getCode() {
        return this.code;
    }

    public String getMsg() {
        return this.msg;
    }

    public String getMsg(String desc) {
        return this.msg + ":" + desc;
    }
}