package com.zz.pay.dao;

import com.zz.pay.model.PayOrderInfo;

public interface PayOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_info
     *
     * @mbggenerated
     */
    int insert(PayOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_info
     *
     * @mbggenerated
     */
    int insertSelective(PayOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_info
     *
     * @mbggenerated
     */
    PayOrderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrderInfo record);
    
    PayOrderInfo selectByOutTradeNo(String outTradeNo);
}