package com.zz.pay.dao;

import com.zz.pay.model.PayOrderRefundInfo;

public interface PayOrderRefundInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    int insert(PayOrderRefundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    int insertSelective(PayOrderRefundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    PayOrderRefundInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrderRefundInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrderRefundInfo record);
}