package com.zz.pay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PayOrderRefundInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.trade_no
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.buyer_logon_id
     *
     * @mbggenerated
     */
    private String buyerLogonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.buyer_user_id
     *
     * @mbggenerated
     */
    private String buyerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.refund_fee
     *
     * @mbggenerated
     */
    private BigDecimal refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.platform_user_no
     *
     * @mbggenerated
     */
    private String platformUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.borrow_nid
     *
     * @mbggenerated
     */
    private String borrowNid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.refund_status
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.gmt_refund_pay
     *
     * @mbggenerated
     */
    private Date gmtRefundPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order_refund_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.id
     *
     * @return the value of pay_order_refund_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.id
     *
     * @param id the value for pay_order_refund_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.out_trade_no
     *
     * @return the value of pay_order_refund_info.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.out_trade_no
     *
     * @param outTradeNo the value for pay_order_refund_info.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.trade_no
     *
     * @return the value of pay_order_refund_info.trade_no
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.trade_no
     *
     * @param tradeNo the value for pay_order_refund_info.trade_no
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.buyer_logon_id
     *
     * @return the value of pay_order_refund_info.buyer_logon_id
     *
     * @mbggenerated
     */
    public String getBuyerLogonId() {
        return buyerLogonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.buyer_logon_id
     *
     * @param buyerLogonId the value for pay_order_refund_info.buyer_logon_id
     *
     * @mbggenerated
     */
    public void setBuyerLogonId(String buyerLogonId) {
        this.buyerLogonId = buyerLogonId == null ? null : buyerLogonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.buyer_user_id
     *
     * @return the value of pay_order_refund_info.buyer_user_id
     *
     * @mbggenerated
     */
    public String getBuyerUserId() {
        return buyerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.buyer_user_id
     *
     * @param buyerUserId the value for pay_order_refund_info.buyer_user_id
     *
     * @mbggenerated
     */
    public void setBuyerUserId(String buyerUserId) {
        this.buyerUserId = buyerUserId == null ? null : buyerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.refund_fee
     *
     * @return the value of pay_order_refund_info.refund_fee
     *
     * @mbggenerated
     */
    public BigDecimal getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.refund_fee
     *
     * @param refundFee the value for pay_order_refund_info.refund_fee
     *
     * @mbggenerated
     */
    public void setRefundFee(BigDecimal refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.pay_type
     *
     * @return the value of pay_order_refund_info.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.pay_type
     *
     * @param payType the value for pay_order_refund_info.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.platform_user_no
     *
     * @return the value of pay_order_refund_info.platform_user_no
     *
     * @mbggenerated
     */
    public String getPlatformUserNo() {
        return platformUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.platform_user_no
     *
     * @param platformUserNo the value for pay_order_refund_info.platform_user_no
     *
     * @mbggenerated
     */
    public void setPlatformUserNo(String platformUserNo) {
        this.platformUserNo = platformUserNo == null ? null : platformUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.borrow_nid
     *
     * @return the value of pay_order_refund_info.borrow_nid
     *
     * @mbggenerated
     */
    public String getBorrowNid() {
        return borrowNid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.borrow_nid
     *
     * @param borrowNid the value for pay_order_refund_info.borrow_nid
     *
     * @mbggenerated
     */
    public void setBorrowNid(String borrowNid) {
        this.borrowNid = borrowNid == null ? null : borrowNid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.refund_status
     *
     * @return the value of pay_order_refund_info.refund_status
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.refund_status
     *
     * @param refundStatus the value for pay_order_refund_info.refund_status
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.gmt_refund_pay
     *
     * @return the value of pay_order_refund_info.gmt_refund_pay
     *
     * @mbggenerated
     */
    public Date getGmtRefundPay() {
        return gmtRefundPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.gmt_refund_pay
     *
     * @param gmtRefundPay the value for pay_order_refund_info.gmt_refund_pay
     *
     * @mbggenerated
     */
    public void setGmtRefundPay(Date gmtRefundPay) {
        this.gmtRefundPay = gmtRefundPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.create_time
     *
     * @return the value of pay_order_refund_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.create_time
     *
     * @param createTime the value for pay_order_refund_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.update_time
     *
     * @return the value of pay_order_refund_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.update_time
     *
     * @param updateTime the value for pay_order_refund_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order_refund_info.remark
     *
     * @return the value of pay_order_refund_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order_refund_info.remark
     *
     * @param remark the value for pay_order_refund_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PayOrderRefundInfo other = (PayOrderRefundInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOutTradeNo() == null ? other.getOutTradeNo() == null : this.getOutTradeNo().equals(other.getOutTradeNo()))
            && (this.getTradeNo() == null ? other.getTradeNo() == null : this.getTradeNo().equals(other.getTradeNo()))
            && (this.getBuyerLogonId() == null ? other.getBuyerLogonId() == null : this.getBuyerLogonId().equals(other.getBuyerLogonId()))
            && (this.getBuyerUserId() == null ? other.getBuyerUserId() == null : this.getBuyerUserId().equals(other.getBuyerUserId()))
            && (this.getRefundFee() == null ? other.getRefundFee() == null : this.getRefundFee().equals(other.getRefundFee()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getPlatformUserNo() == null ? other.getPlatformUserNo() == null : this.getPlatformUserNo().equals(other.getPlatformUserNo()))
            && (this.getBorrowNid() == null ? other.getBorrowNid() == null : this.getBorrowNid().equals(other.getBorrowNid()))
            && (this.getRefundStatus() == null ? other.getRefundStatus() == null : this.getRefundStatus().equals(other.getRefundStatus()))
            && (this.getGmtRefundPay() == null ? other.getGmtRefundPay() == null : this.getGmtRefundPay().equals(other.getGmtRefundPay()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOutTradeNo() == null) ? 0 : getOutTradeNo().hashCode());
        result = prime * result + ((getTradeNo() == null) ? 0 : getTradeNo().hashCode());
        result = prime * result + ((getBuyerLogonId() == null) ? 0 : getBuyerLogonId().hashCode());
        result = prime * result + ((getBuyerUserId() == null) ? 0 : getBuyerUserId().hashCode());
        result = prime * result + ((getRefundFee() == null) ? 0 : getRefundFee().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getPlatformUserNo() == null) ? 0 : getPlatformUserNo().hashCode());
        result = prime * result + ((getBorrowNid() == null) ? 0 : getBorrowNid().hashCode());
        result = prime * result + ((getRefundStatus() == null) ? 0 : getRefundStatus().hashCode());
        result = prime * result + ((getGmtRefundPay() == null) ? 0 : getGmtRefundPay().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_refund_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", outTradeNo=").append(outTradeNo);
        sb.append(", tradeNo=").append(tradeNo);
        sb.append(", buyerLogonId=").append(buyerLogonId);
        sb.append(", buyerUserId=").append(buyerUserId);
        sb.append(", refundFee=").append(refundFee);
        sb.append(", payType=").append(payType);
        sb.append(", platformUserNo=").append(platformUserNo);
        sb.append(", borrowNid=").append(borrowNid);
        sb.append(", refundStatus=").append(refundStatus);
        sb.append(", gmtRefundPay=").append(gmtRefundPay);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}