package com.zz.pay.model;

import java.io.Serializable;
import java.util.Date;

public class PayResponse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_response.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_response.alipay_trade
     *
     * @mbggenerated
     */
    private String alipayTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_response.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_response.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_response.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_response.boby
     *
     * @mbggenerated
     */
    private String boby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_response
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_response.id
     *
     * @return the value of pay_response.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_response.id
     *
     * @param id the value for pay_response.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_response.alipay_trade
     *
     * @return the value of pay_response.alipay_trade
     *
     * @mbggenerated
     */
    public String getAlipayTrade() {
        return alipayTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_response.alipay_trade
     *
     * @param alipayTrade the value for pay_response.alipay_trade
     *
     * @mbggenerated
     */
    public void setAlipayTrade(String alipayTrade) {
        this.alipayTrade = alipayTrade == null ? null : alipayTrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_response.out_trade_no
     *
     * @return the value of pay_response.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_response.out_trade_no
     *
     * @param outTradeNo the value for pay_response.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_response.create_time
     *
     * @return the value of pay_response.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_response.create_time
     *
     * @param createTime the value for pay_response.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_response.update_time
     *
     * @return the value of pay_response.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_response.update_time
     *
     * @param updateTime the value for pay_response.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_response.boby
     *
     * @return the value of pay_response.boby
     *
     * @mbggenerated
     */
    public String getBoby() {
        return boby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_response.boby
     *
     * @param boby the value for pay_response.boby
     *
     * @mbggenerated
     */
    public void setBoby(String boby) {
        this.boby = boby == null ? null : boby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_response
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PayResponse other = (PayResponse) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAlipayTrade() == null ? other.getAlipayTrade() == null : this.getAlipayTrade().equals(other.getAlipayTrade()))
            && (this.getOutTradeNo() == null ? other.getOutTradeNo() == null : this.getOutTradeNo().equals(other.getOutTradeNo()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getBoby() == null ? other.getBoby() == null : this.getBoby().equals(other.getBoby()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_response
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAlipayTrade() == null) ? 0 : getAlipayTrade().hashCode());
        result = prime * result + ((getOutTradeNo() == null) ? 0 : getOutTradeNo().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getBoby() == null) ? 0 : getBoby().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_response
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", alipayTrade=").append(alipayTrade);
        sb.append(", outTradeNo=").append(outTradeNo);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", boby=").append(boby);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}